networks:
  liferay-net:
    name: liferay-net

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: liferay
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes: [mysql-data:/var/lib/mysql]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -proot -h localhost --silent"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [liferay-net]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3 
    container_name: elasticsearch
    ports: ["9200:9200"]
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=10s || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 30
    networks: [liferay-net]

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.16
    container_name: kibana
    ports: ["5601:5601"]
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:5601/api/status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
    networks: [liferay-net]

  liferay:
    image: liferay/portal:7.4.3.132-ga132
    environment:
      LIFERAY_JDBC_DEFAULT_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      LIFERAY_JDBC_DEFAULT_URL: jdbc:mysql://mysql:3306/liferay?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      LIFERAY_JDBC_DEFAULT_USERNAME: ${DB_USER}
      LIFERAY_JDBC_DEFAULT_PASSWORD: ${DB_PASS}
      LIFERAY_DEFAULT_ADMIN_EMAIL_ADDRESS: ${LIFERAY_DEFAULT_ADMIN_EMAIL_ADDRESS}
      LIFERAY_DEFAULT_ADMIN_PASSWORD: ${LIFERAY_DEFAULT_ADMIN_PASSWORD}
      LIFERAY_SETUP_WIZARD_ENABLED: "false"
    depends_on:
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    ports: ["8080:8080"]
    volumes:
      - ./configs/docker/portal-ext.properties:/opt/liferay/portal-ext.properties:ro
      - ./modules:/mnt/liferay/deploy
      - liferay-data:/opt/liferay/data
      - liferay-osgi:/opt/liferay/osgi
    networks: [liferay-net]

volumes:
  liferay-data: {}
  liferay-osgi: {}
  mysql-data: {}
  es-data: {}