# Any instructions here will be appended to the end of the Dockerfile created by `createDockerfile`.FROM liferay/portal:7.4.3.132-ga132
RUN find /opt/liferay/osgi -name "*elasticsearch*embedded*" -delete
RUN find /opt/liferay/osgi -name "*portal*search*elasticsearch*embedded*" -delete